### ISSUE TITLE
Link zu Coloardio Station.xml

### ISSUE THREAD

**Issue by sfratz** [FreieRadios/freieradioapp#2]
die station-xml findest du hier: http://coloradio.org/olaf/station.xml
beste Grüße,
Max

meta.xml  muss angepasst werden.

**Comment by sfratz** [comment]
@breyer Mark kannst du die aktuelle Meta auf den Server legen - danke... app.freefm.de/meta.xml
freieradioapp/002_meta/meta.xml

**Comment by breyer** [comment]
Done. meta.xml wurde eben ausgetauscht.
