### ISSUE TITLE
Wie aktuell/verbindlich ist diese URL?

### ISSUE THREAD

**Issue by AppWerft** [FreieRadios/freieradioapp#72]
https://github.com/FreieRadios/freieradioapp/tree/master/002_meta

**Comment by sfratz** [comment]
Die ist korrekt. Sie wird derzeit manuell auf unseren Server übertragen, nachdem sie hier aktualisiert wird:

Sie läuft und die App kann die Daten auswerten http://app.freefm.de/meta.xml

**Comment by AppWerft** [comment]
Falls ich also meine FreiesRadioApp erweitere sollte ich die Datei aus dem github oder die Zweitere verwenden?

**Comment by sfratz** [comment]
Bitte einlesen, dann ergibt sich die Antwort von selbst: die online laufende…

**Comment by AppWerft** [comment]
Die ist korrekt. Sie wird derzeit manuell auf unseren Server übertragen, 
(auf welchem Server?)
nachdem sie hier aktualisiert wird:
(wo hier?)
===> ist für einen Außenstehenden nicht leicht zu verstehen. ;-)
Sie läuft und 
Wer ist sie?
die App kann die Daten auswerten http://app.freefm.de/meta.xml
OK, ist das jetzt der SinglepointofTruth?

Sorry, für den Dialog, aber mir ist es im Moment nicht ganz klar.

**Comment by sfratz** [comment]
vielleicht wirds hier klarer https://github.com/FreieRadios/freieradioapp/wiki

**Comment by AppWerft** [comment]
Super!

**Comment by sfratz** [comment]
@breyer @Silanus - macht es Sinn es so einzurichten, dass man/jeder/freefm-Teammember die meta.xml von github auf den Server pushen kann?

**Comment by AppWerft** [comment]
Wenn er das Werkzeug „Pushing“ handhaben kann. Ich denke Du meinst `git push …`

**Comment by breyer** [comment]
Wir könnten den Server das regelmässig automatisiert pullen lassen.

**Comment by sfratz** [comment]
die Meta wird nur aktualisiert, wenn ein Radio die Ablage-url für die station-xml ändert oder wenn ein neues Radio hinzukommt. Das ist nicht so oft. Ich hab keine Ahnung was hier besser ist.

**Comment by AppWerft** [comment]
dann würde ich es händisch machen. Alles andere riecht nach Mehraufwand.

**Comment by sfratz** [comment]
@breyer mach wie du denkst ist am besten - pull oder push :-)

**Comment by breyer** [comment]
Wenn ich die history anschaue, hatten wir zwei Änderungen. Am 02.03.2018 und vor 29 Tagen.
Da macht ein Job der alle Stunde läuft keinen Sinn. Halte das auch für zu Fehleranfällig, wenn die Änderung nicht direkt überprüft werden kann.

+1 für händisch

**Comment by sfratz** [comment]
auch bei push?

hatte mir eine Umkehrung der Verantwortung versprochen - im Moment heißt händisch: ich muss mich drum kümmeren und die URLS aktualisieren. Bei push könnte ich allen sagen: schaut da liegts, kümmert Euch selber drum. Aber ich hab wohl übersehen, dass man da dann eh die Requests beantworten muss.

**Comment by sfratz** [comment]
wenn wir da nix machen, dann mach ich den zu :-)
